import { catalogApi, Product } from "@/features/catalog/api"
import { posApi, POSProduct } from "@/features/pos/api"

/**
 * Normalizes a scanned barcode string:
 * - Trims whitespace & control characters
 * - Strips newlines and carriage returns
 * - If encoded as a JSON QR string, extracts 'barcode' or 'sku' or 'id'
 * - Strictly preserves leading zeros and string identity (never cast to number)
 */
export function normalizeBarcode(raw: string): string {
  if (!raw) return ""
  let code = raw.trim()

  // Unescape accidental surrounding quotes
  if ((code.startsWith('"') && code.endsWith('"')) || (code.startsWith("'") && code.endsWith("'"))) {
    code = code.slice(1, -1).trim()
  }

  // Handle JSON embedded barcodes (e.g. from QR codes generated by the ERP or external inventory labels)
  if (code.startsWith("{") && code.endsWith("}")) {
    try {
      const parsed = JSON.parse(code)
      if (typeof parsed === "object" && parsed !== null) {
        const extracted = parsed.barcode || parsed.sku || parsed.id || parsed.code
        if (extracted) {
          code = String(extracted).trim()
        }
      }
    } catch {
      // Not valid JSON, keep as raw string
    }
  }

  return code
}

/**
 * Audio feedback on successful scan using Web Audio API (cross-browser without external asset files).
 */
export function playScanBeep(): void {
  try {
    const AudioContextClass = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext
    if (!AudioContextClass) return
    const ctx = new AudioContextClass()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()

    osc.type = "sine"
    osc.frequency.setValueAtTime(1800, ctx.currentTime) // Crisp POS beep tone
    gain.gain.setValueAtTime(0.15, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.12)

    osc.connect(gain)
    gain.connect(ctx.destination)

    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.12)
  } catch {
    // AudioContext blocked or not supported
  }
}

/**
 * Haptic feedback on mobile devices supporting Navigator.vibrate.
 */
export function triggerHapticFeedback(): void {
  try {
    if (typeof navigator !== "undefined" && typeof navigator.vibrate === "function") {
      navigator.vibrate(100)
    }
  } catch {
    // Vibration not permitted or supported
  }
}

/**
 * Centralized service for catalog product barcode lookup.
 */
export async function lookupCatalogProduct(barcode: string): Promise<Product> {
  const clean = normalizeBarcode(barcode)
  if (!clean) {
    throw new Error("Barcode cannot be empty")
  }
  return catalogApi.lookupBarcode(clean)
}

/**
 * Centralized service for POS product barcode lookup.
 */
export async function lookupPOSProduct(barcode: string): Promise<POSProduct> {
  const clean = normalizeBarcode(barcode)
  if (!clean) {
    throw new Error("Barcode cannot be empty")
  }
  return posApi.lookupBarcode(clean)
}
